require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - db/seeds.rb
    - Gemfile
    - Rakefile
    - config/initializers/*.rb
    - bin/*
    - Gists.thor

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'it']

Layout/LineLength:
  Max: 100

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/infra/*

RSpec/ExampleLength:
  Max: 15

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
