version: 2
jobs:
  build:

    working_directory: ~/app

    docker:
      - image: cimg/ruby:2.6.3
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

    steps:

      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: ./go linter
      - run: ./go test

workflows:
  version: 2
  pipeline:
    jobs:
      - build
